language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - npm run lint
  - npm run cover
  - npm run dist

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
